### ISSUE TITLE
Update to the DigiByte Itegration Guide to v2.0

### ISSUE THREAD

**Issue by DGBNOOB** [DigiByte-Core/DGBio#55]
The DigiByte Integration guide was shared on social media and should be added to the website. This will benefit DigiByte and the integrators with references in the guidelines and changes talked about in best practices. https://drive.google.com/file/d/1K3nxEYTDGV0eq437Ys-v6J0FDurk2E5Y/view

**Comment by makyurt** [comment]
Updated integration guide is now online. Because it has same link way, It may need to force browser cache refresh.
