### ISSUE TITLE
DCRDEX & Komodo Wallet DEX

### ISSUE THREAD

**Issue by DGBNOOB** [DigiByte-Core/DGBio#56]
Recommend adding the DCRDEX and AtomicDEX widgets on the English version of the website because the U.S. based exchanges and users were impacted the greatest. No translation needed.
Different language versions of the website have different exchange information, the above changes wouldn't affect the other language versions.

![Screenshot 2023-07-01 133242](https://github.com/DigiByte-Core/DGBio/assets/136190014/8d97da10-5f47-4adf-9b29-52c54c337ac6)
  
Due to regulatory uncertainty Centralized Exchanges are shutting down or not servicing customers in certain geographic locations. DigiByte has recently been added to DCRDEX and AtomicDex. I recommend adding DCRDEX and AtomicDEX to the Quick picks from the DigiByte ecosystem on digibyte.org.
![Screenshot 2023-06-20 133252](https://github.com/DigiByte-Core/DGBio/assets/136190014/41890aff-4205-420c-be94-7c0bae994a9d)

For widget description I think keeping it simple: DCRDEX Decred-Decentralized Exchange in English 
Link to DCRDEX:  https://dex.decred.org/
symbol-negative-gradient png file is the one used on DCRDEX
[Dcrdex.-.logo.package.-.v1.-.RGB.zip](https://github.com/DigiByte-Core/DGBio/files/11807337/Dcrdex.-.logo.package.-.v1.-.RGB.zip)

Widget description: AtomicDEX-Decentralized Exchange in English 
Link to AtomicDEX:  https://atomicdex.io/en/
Folder labeled Mark-AtomicDEX_Mark-Color is the one used on AtomicDEX
[AtomicDEX_Brand_Assets.zip](https://github.com/DigiByte-Core/DGBio/files/11807342/AtomicDEX_Brand_Assets.zip)

Let me know if I can do anything help.
-Jose

**Comment by ycagel** [comment]
Jose, thanks for submitting this.  Someone will make the website code change, and open a PR that references that issue. Once completed, we can add reviewers to that. Does that make sense?

**Comment by DGBNOOB** [comment]
Thank you for your response. Sounds great and makes sense. I'm still trying to figure out these processes to better understand and be more involved. I know that the website might not be the priority in development, however, this is a great source of information for anyone seeking to learn about DigiByte. I have a list of other recommendations to improve the website but for now one issue at a time. Thank you everyone.
-Jose

**Comment by ycagel** [comment]
Jose, 
 Do you know anyone from the community that can implement these changes on the website and then submit a PR?

**Comment by DGBNOOB** [comment]
I'm watching a few videos to learn how to do it, I'd like to do it.

**Comment by DGBNOOB** [comment]
I don't know anyone who will make the changes. I'll leave this open for anyone who is capable and available to do it.

**Comment by Sbosvk** [comment]
> "Different language versions of the website have different exchange information, the above changes wouldn't affect the other language versions."

@DGBNOOB 
Can you please show me this in form of screenshot or whatever? Which languages in particular, if you know?
Information shouldn't differ across different translations of the site, so this might be another issue we need to raise and get sorted out.

**Comment by DGBNOOB** [comment]
I didn't go through all the different language versions but here are a few variations of quick picks exchange info. I get what you're saying about having uniformity of information. In this particular section different exchanges service different geographic locations.

I opened this issue to add DCRDEX and AtomicDEX because Binance.US is having regulatory issues in the US, Bittrex is no longer servicing the US, ABRA is going out of business or already out of business. These issues probably don't affect other geographic locations with different regulatory environments. Adding these to DEX's to the English version of the website gives people more options in acquiring DGB.   

![Screenshot 2023-07-02 090442](https://github.com/DigiByte-Core/DGBio/assets/136190014/5c89c7c8-a964-4d9e-962e-04d51626ee97)
![Screenshot 2023-07-02 090708](https://github.com/DigiByte-Core/DGBio/assets/136190014/4cd863b9-7c31-4fb4-bf7a-e88bf0f0bb8e)
![Screenshot 2023-07-02 091009](https://github.com/DigiByte-Core/DGBio/assets/136190014/bbdee6ae-39d4-4761-ba1b-cceb5860c6a9)

**Comment by DGBNOOB** [comment]
Komodo's AtomicDEX recently rebranded to Komodo Wallet. The logos have also been updated, in the attached zipped file, Click folder labeled Komodo Brand Assets_23 - _Komodo Platform and there's a link to Komodo_Style_Guide2019-V2 which covers appropriate use of the logo. p.16 gives guidance on application of logo and display size. 

Komodo_Brand_Assets_23(1)-Komodo Brand Assets_23-_Komodo Platform-PNG-Mark. 
I think the Mark Color PNG file logo works for the widget display on the website.

![Mark-Color](https://github.com/DigiByte-Core/DGBio/assets/136190014/712888e2-ada1-4a8b-ba05-89322574f3bb)

[Komodo_Brand_Assets_23.zip](https://github.com/DigiByte-Core/DGBio/files/12221628/Komodo_Brand_Assets_23.zip)

**Comment by ycagel** [comment]
This has been resolved through PR https://github.com/DigiByte-Core/DGBio/pull/89.
