### ISSUE TITLE
Donation widget

### ISSUE THREAD

**Issue by DGBNOOB** [DigiByte-Core/DGBio#58]
Recommend removing the Donation widget upper right corner, no translation required.

![Screenshot 2023-07-01 121041](https://github.com/DigiByte-Core/DGBio/assets/136190014/7e4fc14a-5fae-4872-8d58-07b61d43c2b2)

The Donation button redirects the viewer to dgbwiki, which talks about the DigiByte Foundation and The DigiByte Awareness Team. 

The Donation widget is next to the Foundation, DGBAT and the Alliance widgets and donation info can be found there. Due to recent conversations about bookkeeping and transparency, my recommendation is that each DigiByte supporting entity collect donations through their respective websites. This gives the website anonymity from donations given to supporting agencies.

**Comment by Sbosvk** [comment]
Ack.

**Comment by DGBNOOB** [comment]
The Donate widget has been removed, thank you. This issue is closed.
