### ISSUE TITLE
Learn more widget

### ISSUE THREAD

**Issue by DGBNOOB** [DigiByte-Core/DGBio#60]
Recommend repurposing the Learn More widget to redirect to Social Media. Requires Translation, however, the translation is already there-cut and paste to relabel the widget.

Currently when you click on the Learn More button it moves the website down about an inch to the first topic “What makes DigiByte stronger than others?”, which is literally right below the Learn More button. My recommendation is creating a link to Social media which is right next to Telegram groups, IMO this where the community does most of its work in educating, spreading awareness and assisting with issues. There are social media widgets on the landing page on a laptop screen, however, the user interface is different on mobile devices than it is on laptop and mobile users can't see the social media widgets same as laptop users. Repurposing the learn more widget to social media will help viewers connect with the community. 

(Learn More 1/3)
![Screenshot 2023-07-01 120311](https://github.com/DigiByte-Core/DGBio/assets/136190014/fcc7812b-914f-4a9c-b8dc-ef0025ce2c81)
(Social Media English 2/3)
![Screenshot 2023-07-01 134750](https://github.com/DigiByte-Core/DGBio/assets/136190014/fc162e8c-6959-41dc-93b9-57783c2d05da)
(Social Media Deutsch 3/3)
![Screenshot 2023-07-01 135631](https://github.com/DigiByte-Core/DGBio/assets/136190014/cf25ed48-a6f5-4644-ae28-67c20b1e65c8)

**Comment by Sbosvk** [comment]
Great idea.

**Comment by DGBNOOB** [comment]
Excellent work on PR#87
