### ISSUE TITLE
Buy DGB widget

### ISSUE THREAD

**Issue by DGBNOOB** [DigiByte-Core/DGBio#61]
Recommend repurposing the Buy DGB widget to redirect to the Documentation & Guides and labeling the widget to Guides for short. Requires translation, however, the translation is there.  

Currently when you click on the Buy DGB button it takes you to Quick picks from the DigiByte Ecosystem and right below you can find several exchanges. There’s a Currency button at the top of the page which does the same thing. In my opinion, the Buy button gives the wrong message. Do we want the website to give the impression to viewers to buy DGB before learning about DigiByte? To me that’s putting the horse before the cart, it’s backwards. Some of the documents need to be updated such as the media sheet and info paper in the Documentation & Guides section, that can be a separate initiative. Repurposing the Buy DGB widget to Guides helps as a short cut for viewers interested in viewing the Documents & Guides.

(1/3 Buy DGB widget)
![Screenshot 2023-07-01 120311](https://github.com/DigiByte-Core/DGBio/assets/136190014/0e5dfcd3-9d61-4398-bb42-cc8e078f01d4)
(2/3 English Documentation & Guides)
![Screenshot 2023-07-01 143201](https://github.com/DigiByte-Core/DGBio/assets/136190014/a0f55978-4024-42de-9cdb-e100cb87ea83)
(3/3 Afrikaans version)
![Screenshot 2023-07-01 143350](https://github.com/DigiByte-Core/DGBio/assets/136190014/fdccf102-7434-4c94-ad9e-4f106477d2d0)

**Comment by DennisPitallano** [comment]
@DGBNOOB 
I'll be working on this issue, let me know if there are any changes to the requirements.

**Comment by DGBNOOB** [comment]
At this time I think we should wait for input from @Sbosvk.

**Comment by Sbosvk** [comment]
I personally don't think there should even be a "buy" button because this gives the impression of actually being able to buy directly on the website. I think we can wrap this package differently so to speak.

**Comment by DGBNOOB** [comment]
Lets move forward on repurposing the buy button to Documents & Guides. If Documents & Guides is to long shorten it to Guides.

**Comment by DennisPitallano** [comment]
Hi @DGBNOOB @Sbosvk 
what do you think?

desktop
![image](https://github.com/DigiByte-Core/DGBio/assets/3394208/8ca9990d-4a73-446a-8386-694f294b0342)

mobile
![image](https://github.com/DigiByte-Core/DGBio/assets/3394208/9ab54aa5-cfea-4bac-a5a8-39edd53f220b)

**Comment by DGBNOOB** [comment]
I think we should change it to Guides. Guides will center and look better. Thank you for the visual.

**Comment by Sbosvk** [comment]
I think we can use the common expression "Docs" - "Docs and Guides". I don't think that we want to leave out Docs/Documentation as the section is not explicitly only for guides, but also for docs.

- Simply "Documentation" works too, as this is an umbrella terminology that encompasses guides as well.

**Comment by DennisPitallano** [comment]
preview 
Desktop
![image](https://github.com/DigiByte-Core/DGBio/assets/3394208/7c6e4b99-ab2c-4832-b5bc-060727f0ca98)
Mobile
![image](https://github.com/DigiByte-Core/DGBio/assets/3394208/f80b2f33-8f22-4504-9b8b-000f50f88fee)

**Comment by DennisPitallano** [comment]
Hi @DGBNOOB , @Sbosvk 
Is it acceptable to use "Docs and Guides" for English translations and "Documentation" for translations in other languages? We currently lack translations for "Docs and Guides" in other languages, but we do have translations available for "Documentation" that we can use.

**Comment by Sbosvk** [comment]
Good point, @DennisPitallano! I think that sounds good!

**Comment by DGBNOOB** [comment]
I concur.

**Comment by ycagel** [comment]
Looks great. Did you mean to keep the PR in draft mode?

**Comment by DennisPitallano** [comment]
@ycagel 
yes, I initially created the PR in draft mode, I plan to add more commits to it later on before marking it as Ready for review.

**Comment by ycagel** [comment]
This has been resolved through PR https://github.com/DigiByte-Core/DGBio/pull/91.
