### ISSUE TITLE
Digi-Broker & DigiAsset Tools

### ISSUE THREAD

**Issue by DGBNOOB** [DigiByte-Core/DGBio#64]
DigiAssets supported services embedded link takes you down to see DigiAssets in action which has three tiles’ services. 

No translation required. Recommend removing Digi-Broker if they’re not v3 DigiAsset compatible, plus their website isn’t working. Recommend removing DigiAsset Tools since its admin only and most likely not v3 DigiAsset compatible. These services might have supported DigiByte at one point, however, currently they're not adding value to the website, DigiByte or the DigiAssets protocol. 

(1/3 DigiAsset Supported services DigiBroker and DigiAsset Tools)
![Screenshot 2023-07-01 162851](https://github.com/DigiByte-Core/DGBio/assets/136190014/b9156aa9-a883-4414-b74f-fe673b071e8e)
(2/3 Digi-Broker website login/password recovery not working. No longer supports Digi-ID login)
![Screenshot 2023-07-01 162413](https://github.com/DigiByte-Core/DGBio/assets/136190014/6330c9cf-f764-47ec-8477-3ad48fd56776)
(3/3 DigiAsset Tools admin only)
![Screenshot 2023-07-01 162526](https://github.com/DigiByte-Core/DGBio/assets/136190014/440040e8-e652-47c7-9eed-dbca16242447)

**Comment by ycagel** [comment]
This has been resolved through PR https://github.com/DigiByte-Core/DGBio/pull/89.
