### ISSUE TITLE
Store Trade DigiAssets

### ISSUE THREAD

**Issue by DGBNOOB** [DigiByte-Core/DGBio#65]
Store/Trade
Recommend replacing DigiByte Mobile with DigiAssetX and removing redirect link. The DigiAsset supported services has the link to DigiAssetX.com. 

Example "Use the DigiAssetX application to send, accept and store your assets or explore DigiAsset supported services to buy sell and swap DigiAssets".  No translation needed since its a proper noun company/product and no literal translation in other languages. DigiAssetX is the only platform currently supporting v3 DigiAssets Store/Trade.

![Screenshot 2023-07-01 164406](https://github.com/DigiByte-Core/DGBio/assets/136190014/29f7b7d5-9ca9-4ada-a1c5-34055a5aa5c9)

**Comment by Sbosvk** [comment]
I'm all for it. But will also need clarification that this is just one app that CAN be used for it rather than THE one.

**Comment by DGBNOOB** [comment]
I recommended replacing DigiByte mobile with DigiAssetX to make it a simple change, but you're correct it should read: You can use the DigiAssetX application-since it's not the only option with more options coming to store/trade v3 DigiAssets. 

This changes my assessment of no translation needed to translation needed. Let me know what I can do to help.
I think your feedback, time and recommendations are valuable. Thank you.

**Comment by DGBNOOB** [comment]
Closing and rewriting the issue and recommended solution.
