### ISSUE TITLE
Digi-ID Scanning 

### ISSUE THREAD

**Issue by DGBNOOB** [DigiByte-Core/DGBio#66]
2 Scanning.
Recommend replacing DigiByte Mobile with Digi-ID/AntumID. No translation required. Redirect link for Digi-ID/AntumID not needed since "Digi-ID supported apps" has a link to Digi-ID/AntumID iOS. 

The Digi-ID authenticator can serve more purposes than crypto related logins. If someone is interested in integrating Digi-ID authentication to their website and they don't care about crypto, they can download this stand alone app with out a cryptocurrency wallet attached to it. 

The Digi-ID Android application needs to be made available as well (issue for Digi-ID.io repository).     

Example: The user scans the QR code from the Digi-ID/Antum-ID or any Digi-ID supported app.

![Screenshot 2023-07-01 170629](https://github.com/DigiByte-Core/DGBio/assets/136190014/4b5fa98f-4503-426d-8d08-a1c261d303b6)

**Comment by Sbosvk** [comment]
Since there has not yet been a re-upload of the Digi-ID/AntumID application for android I will simply only remove DigiByte Mobile link from this section, and will also remove the android link from the `digiidapps` section.

**Comment by DGBNOOB** [comment]
I know we're breaking these issues down to small manageable chunks but I want to include this issue here. We can finish here first and then take a look at digi-id-io repo, since this is Digi-ID related. Let me know what you think [https://github.com/DigiByte-Core/digi-id-io/issues/3#issue-1784408236](url).  

@DennisPitallano @Sbosvk

**Comment by Sbosvk** [comment]
@DGBNOOB i just closed out the issue you referred to, and merged the changes. Having issues with the CI/CD right now but will re-run the jobs in a bit.

**Comment by ycagel** [comment]
Has this been resolved?

**Comment by DennisPitallano** [comment]
Hi @DGBNOOB, 
is the link issue related to https://github.com/DigiByte-Core/DGBio/issues/93?
I just noticed that the anchor link [DigiByte Mobile](https://www.digibyte.org/?lang=en#dgbmobile) is related to 
![image](https://github.com/DigiByte-Core/DGBio/assets/3394208/779c4246-d711-4221-a218-525f5ea94451)

and the anchor link [Digi-ID supported app](https://www.digibyte.org/?lang=en#digidapps) is linked to 
![image](https://github.com/DigiByte-Core/DGBio/assets/3394208/82930abc-4a63-4c76-a948-1f352d8be4a9)

**Comment by DGBNOOB** [comment]
Great question, after receiving input from @Sbosvk the solution is to remove the DigiByte Mobile wallet and anchor from the sentence. However, keep anchor to Digi-I’d supported apps. my original suggestion was to change the url, however, as Sbosvk pointed out that the Digi-ID/Antum has not yet been re-uploaded

With edit, the sentence should read:
 “The user scans the QR code from any Digi-ID supported app”.

Issue #93 is only related because of the anchor. 
Let me know if that makes sense.

**Comment by DennisPitallano** [comment]
I've gone ahead and made the changes, including translations for other languages. Now we just need to give these translations a good proofread. 📑🧑‍💻😊

1. **Afrikaans**: Die gebruiker skandeer die QR-kode vanaf enige Digi-ID-ondersteunde program.
2. **Czech**: Uživatel skenuje QR kód z libovolné aplikace podporující Digi-ID.
3. **Danish**: Brugeren scanner QR-koden fra enhver Digi-ID-understøttet app.
4. **Spanish**: El usuario escanea el código QR desde cualquier aplicación compatible con Digi-ID.
5. **French**: L'utilisateur scanne le code QR depuis n'importe quelle application compatible avec Digi-ID.
6. **Croatian**: Korisnik skenira QR kod iz bilo koje aplikacije koja podržava Digi-ID.
7. **Indonesian**: Pengguna memindai kode QR dari aplikasi yang didukung Digi-ID.
8. **Swahili**: Mtumiaji huchambua nambari ya QR kutoka kwa programu yoyote inayoungwa mkono na Digi-ID.
9. **Hungarian**: A felhasználó bármely Digi-ID-t támogató alkalmazásból beolvasztja a QR-kódot.
10. **Malay**: Pengguna mengimbas kod QR dari mana-mana aplikasi yang disokong oleh Digi-ID.
11. **Norwegian**: Brukeren skanner QR-koden fra en hvilken som helst Digi-ID-støttet app.
12. **Dutch**: De gebruiker scant de QR-code vanuit elke Digi-ID-ondersteunde app.
13. **Filipino**: Ang user ay nag-scan ng QR code mula sa anumang app na suportado ng Digi-ID.
14. **Polish**: Użytkownik skanuje kod QR z dowolnej aplikacji obsługującej Digi-ID.
15. **Portuguese**: O usuário escaneia o código QR de qualquer aplicativo suportado pelo Digi-ID.
16. **Romanian**: Utilizatorul scanează codul QR din orice aplicație suportată de Digi-ID.
17. **Albanian**: Përdoruesi skanon kodin QR nga çdo aplikacion i mbështetur nga Digi-ID.
18. **Slovenian**: Uporabnik skenira QR kodo iz katere koli aplikacije, ki jo podpira Digi-ID.
19. **Finnish**: Käyttäjä skannaa QR-koodin mistä tahansa Digi-ID-tuettavasta sovelluksesta.
20. **Swedish**: Användaren skannar QR-koden från vilken Digi-ID-stödd app som helst.
21. **Vietnamese**: Người dùng quét mã QR từ bất kỳ ứng dụng nào được hỗ trợ bởi Digi-ID.
22. **Turkish**: Kullanıcı, Digi-ID tarafından desteklenen herhangi bir uygulamadan QR kodunu tarar.
23. **Russian**: Пользователь сканирует QR-код из любого приложения, поддерживающего Digi-ID.
24. **Bulgarian**: Потребителят сканира QR кода от всяко приложение, поддържащо Digi-ID.
25. **Greek**: Ο χρήστης σκανάρει τον κωδικό QR από οποιαδήποτε εφαρμογή που υποστηρίζει το Digi-ID.
26. **Hindi**: उपयोगकर्ता किसी भी डिजी-आईडी समर्थित ऐप से QR कोड स्कैन करता है।
27. **Thai**: ผู้ใช้สแกนรหัส QR จากแอปที่รองรับ Digi-ID ใด ๆ
28. **Japanese**: ユーザーは、Digi-IDをサポートするアプリからQRコードをスキャンします。
29. **Korean**: 사용자는 Digi-ID를 지원하는 모든 앱에서 QR 코드를 스캔합니다.
30. **Chinese** (Simplified): 用户可以从任何支持Digi-ID的应用程序扫描QR码。
31. **Persian**: کاربر کد QR را از هر برنامه‌ای که Digi-ID را پشتیبانی می‌کند، اسکن می‌کند.

**Comment by ycagel** [comment]
This has been resolved through PR https://github.com/DigiByte-Core/DGBio/pull/99.
