### ISSUE TITLE
Apps developed by the community

### ISSUE THREAD

**Issue by DGBNOOB** [DigiByte-Core/DGBio#70]
Apps developed by the DigiByte community.  

Recommend replacing information about DigiByte mobile with Digi-ID, DigiAssets and other applications developed by the community.

Requires little or no translation because some of these products don't have a literal translation in other languages.

Top line in bold Digi-ID & DigiAssets replacing DigiByte Mobile
Digi-ID/AntumID replacing SPV wallet
DigiAssetX replacing Digi-ID support
DigiSweep replacing DigiAsset Support
DigiByte Domains replacing multi language support 

Replace App store icon with Digi-ID icon – with link that redirects to Digi-ID supported apps section of the website 

Replace Android app icon with DigiAssetsX icon – link that redirects to DigiAssetX

Disable links to Apple test flight and Android Beta and reserve tabs for Securus wallet iOS/Andriod 

Relabel Support widget as Digibyte Domains and link to DigiByt Domains Home: https://digibytedomains.com/

Relabel Recovery widget as DigiSweep

![Screenshot 2023-07-01 181854](https://github.com/DigiByte-Core/DGBio/assets/136190014/ba17b975-36f9-40bb-bcee-c45a31412994)

**Comment by Sbosvk** [comment]
It is my personal opinion that this section should only include official downloads, and as such, only DigiByte Core.

**Comment by DGBNOOB** [comment]
I agree. I made the recommendations to change the info in the DigiByte Mobile box to keep some balance. Another option is to remove the box all together and center the DigiByte Core box. The information I recommended can go in a more suitable location on the website that's visible but doesn't represent itself as official . In my opinion, removing the DigiByte mobile app images, videos, download links and any mention of it should be priority.

**Comment by DGBNOOB** [comment]
Before any work is started on this issue, should it be closed and written again or discus the change here and keep all previous comments. 
@Sbosvk

**Comment by Sbosvk** [comment]
I would say most of these suggestions have been deprecated, so I would rather we closed this issue. If you want to create one for removing digibyte mobile that would be good, but I disagree with replacing it with anything.

**Comment by DGBNOOB** [comment]
Will close and rewrite with above input.
