### ISSUE TITLE
DigiByte blockchain stats

### ISSUE THREAD

**Issue by DGBNOOB** [DigiByte-Core/DGBio#74]
![DigiByte Blockchain _ DGB Coin _ DigiAssets _ Digi-ID - Google Chrome 11_8_2023 11_11_24 AM](https://github.com/DigiByte-Core/DGBio/assets/136190014/fb615888-e909-4a9b-839d-040bf55853e0)
Blocks produced is reading 0 and the node downloaded says NaN. I'm viewing this issue on HP Laptop.

**Comment by Sbosvk** [comment]
Issue is because these used to work with PHP scripts, but GitHub pages does not have PHP support. New scripts needs to be written in JavaScript to replace.

**Comment by DGBNOOB** [comment]
Thank you for your response, I will notify the community member who brought this issue up.

**Comment by DennisPitallano** [comment]
@DGBNOOB @Sbosvk 
I have given priority to this issue as it could lead to misinformation for visitors of the website regarding the current stats of the DigiByte blockchain.
