### ISSUE TITLE
Remove DigiByte Foundation 

### ISSUE THREAD

**Issue by DGBNOOB** [DigiByte-Core/DGBio#77]
![remove foundation ](https://github.com/DigiByte-Core/DGBio/assets/136190014/d6729826-453c-465d-99f8-a597bc590648)

The DigiByte Foundation dissolved their their organization. There are a few other places on the website that they're mentioned, I'll create separate issues for them.

**Comment by DennisPitallano** [comment]
Regarding the development update,
 I've also made changes to the site footer section by removing the DigiByte Foundation link.
 
 commit here: https://github.com/DigiByte-Core/DGBio/pull/84/commits/e1df74ddb8c02b643955fc4f6ffef4e37d0ed464
 
![image](https://github.com/DigiByte-Core/DGBio/assets/3394208/486e0bc8-c57c-4fd3-bfff-a25f08200a79)

**Comment by DGBNOOB** [comment]
Also in community section.
![DigiByte Foundation](https://github.com/DigiByte-Core/DGBio/assets/136190014/d275c480-70e1-4fba-8a29-b6ff7c5ea651)

**Comment by DennisPitallano** [comment]
Noted. will remove that section also.
![image](https://github.com/DigiByte-Core/DGBio/assets/3394208/3a5b840a-959b-490a-b1e6-1e70c6978536)

**Comment by DGBNOOB** [comment]
I can't say thank you enough.

**Comment by DennisPitallano** [comment]
I just noticed that the "DigiByte Alliance" section in the community tab is only in English right now. It's not available in other languages yet.

@DGBNOOB can you create a new issue ticket for this? so we can sync it to the other languages, also for change tracking.
   
![image](https://github.com/DigiByte-Core/DGBio/assets/3394208/44955cc6-1621-4841-b247-2a6be1d70acc)

**Comment by DGBNOOB** [comment]
Great job

**Comment by DGBNOOB** [comment]
Great job
