### ISSUE TITLE
More secure

### ISSUE THREAD

**Issue by DGBNOOB** [DigiByte-Core/DGBio#79]
![delete for asic resistance](https://github.com/DigiByte-Core/DGBio/assets/136190014/ec21f066-ed3e-4283-b4c9-7aafb49d1d49)

The sentence, "One of which is Odocrypt that changes itself every 10 days for asic resistance" should be edited and end the sentence at 10 days. and remove "for asic resistance" since the algorithm has been optimized.

**Comment by DennisPitallano** [comment]
@DGBNOOB 

I've gone ahead and made the changes just for the English translations. Could we also figure out which part of the paragraph needs adjusting in the other languages? The way the paragraph is put together might vary in different languages, so we shouldn't assume what needs to be removed.

cheers;

**Comment by DGBNOOB** [comment]
Just to give you a little context, The odocrypt algorithm is an FPGA mined algo, however, there has been hardware made to optimize it and only a small group miners/pools have access to the hardware. The Reddit post below should help anyone reading this comment get a good understanding. The edit should read "One of which is Odocrypt that changes itself every 10 days." this is an accurate statement, however, no longer asic resistant needs to be removed "**for asic resistance**". 

Translation is a challenge since English to other languages don't translate literally and this is new technology with terms not yet used or adopted in other regions of the world. 

Great question let me know if you need further clarification or let us know if you're running into obstacles due to translation. I have an idea how we can work through this.

[https://www.reddit.com/r/Digibyte/comments/lruer5/comment/goq21a7/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button](url)

**Comment by DennisPitallano** [comment]
The only thing that's holding me back right now is the translations. I'd love to hear your ideas on how we can tackle this together.

**Comment by ycagel** [comment]
@DGBNOOB  Any strategy on how we can figure out the translation piece to continue making progress?

**Comment by DGBNOOB** [comment]
My recommendation is to update the English version first so that it can serve as the example for the other language versions. If you read the last two comments on issue #82, I think we can create a strategy for getting non-English versions translated and proofread to ensure accuracy. Once English version is updated then we can ask the community across the different social networks for volunteers to proofread, @Sbosvk has translating software.

**Comment by DennisPitallano** [comment]
Hi @DGBNOOB 
Should we wait for the other translations to be completed before including the updated English version in a Pull Request, or can I go ahead and include it?

**Comment by DGBNOOB** [comment]
At this time I think we should wait to hear some input from @Sbosvk, I think that if the English version is updated then it can serve as the example for translating the other language versions, Sbosvk has translation software, however then we need native speaking volunteers to proofread other language versions.

**Comment by Sbosvk** [comment]
Let's do translations later.

**Comment by DGBNOOB** [comment]
@DennisPitallano Let’s move forward with English translation only

**Comment by DennisPitallano** [comment]
preview of the change.
![image](https://github.com/DigiByte-Core/DGBio/assets/3394208/b5d4b5bf-9273-400b-8258-1eb2e99f2552)

**Comment by DGBNOOB** [comment]
Looks good to me.

**Comment by ycagel** [comment]
This has been resolved through PR https://github.com/DigiByte-Core/DGBio/pull/91.
