### ISSUE TITLE
Much faster

### ISSUE THREAD

**Issue by DGBNOOB** [DigiByte-Core/DGBio#80]
![More secure](https://github.com/DigiByte-Core/DGBio/assets/136190014/4463f274-e0e4-4f88-ac01-e7d49e70cb46)

recommend editing "early segwit implementation and blockchain rigidity enable up to 1066 on-chain transactions per second with negligible fees" to read "early segwit implementation theoretically enables up to 1066 on-chain transactions per second with negligible fees". Once there is a conclusive answer then update the number of transactions.

**Comment by DennisPitallano** [comment]
same with issue #79 
Could we also figure out which part of the paragraph needs adjusting in the other languages?

**Comment by DGBNOOB** [comment]
The modification is to add that SegWit x4 theoretically enables 1066 transactions per second (TPS) for issues #79 & #80. For context we have information that's commonly referenced that says SegWit x4 enables 1066 transactions per second (TPS) on the DigiByte Blockchain. This is a contentious issue among community members and it needs to be tested in a testing environment and then on main for an accurate TPS count. This has been attempted which has resulted in disruption of explorer services and the person who attempted this test states that 1066 TPS is not an accurate number. So what we want people to understand is that Segwit x4 can theoretically process 1066 TPS and we can leave it at that-until it's tested and we can record an accurate number.

Let me know if this helps or if anyone has any questions on this comment.

**Comment by DennisPitallano** [comment]
Hi @DGBNOOB 
The changes for this issue have been reverted (c380ed56720e03d44447a3d1f240a68e6d606b59) in the last Pull Request. Are we still proceeding with this update?

**Comment by DGBNOOB** [comment]
At this time I think we should wait for input from @Sbosvk. I still think the English version should be completed first to serve as the example for the other language versions.

**Comment by Sbosvk** [comment]
I think we could take this one step further and simply state that SegWit enables up to 4 times amount of TPS. There's no point mentioning a theoretical number that we all know to not be true in nearly any real-world situation.

**Comment by DGBNOOB** [comment]
Works perfectly. Let’s apply the same statement to #82 SegWit enables up to four times amount of TPS, disregard “theoretical”. Continue with English version translation only.

**Comment by DennisPitallano** [comment]
Hi @DGBNOOB @Sbosvk 
Showing the preview of the change, Could you please confirm if this aligns with our expectations?
I replaced "four times" with "4x" to keep it consistent with "40x" and "10x".
![image](https://github.com/DigiByte-Core/DGBio/assets/3394208/68b4cf1c-9609-400f-ad67-eeff2b71d922)

**Comment by DGBNOOB** [comment]
That looks good to me

**Comment by Sbosvk** [comment]
Looks good, I will review this evening if time allow, or possibly tomorrow morning (in about 12h).

**Comment by ycagel** [comment]
This has been resolved through PR https://github.com/DigiByte-Core/DGBio/pull/91.
