### ISSUE TITLE
forward thinking

### ISSUE THREAD

**Issue by DGBNOOB** [DigiByte-Core/DGBio#81]
![Screenshot 2024-03-07 103929](https://github.com/DigiByte-Core/DGBio/assets/136190014/432864bc-e7f6-4903-b408-3cd40fab3f6d)

Delete "over the past 9 years," this is redundant since its already been stated that DigiByte was created in late 2013 and released in 2014, same issue of having to manually change the number of years. The sentence should begin at "DigiByte has repeatedly".

**Comment by DennisPitallano** [comment]
same with issue #79 
Could we also figure out which part of the paragraph needs adjusting in the other languages?

**Comment by DennisPitallano** [comment]
@DGBNOOB 
Can we implement a similar solution as demonstrated in https://github.com/DigiByte-Core/DGBio/issues/78#issuecomment-1996531072? 
This way, we would automatically calculate the year, eliminating the need to worry about other translations.

**Comment by DGBNOOB** [comment]
That would be a great solution to this issue, yes same as #78.

**Comment by ycagel** [comment]
This has been resolved through PR https://github.com/DigiByte-Core/DGBio/pull/89.
