### ISSUE TITLE
Crypto Bantam

### ISSUE THREAD

**Issue by DGBNOOB** [DigiByte-Core/DGBio#85]
Crypto Bantam doesn't have any DigiByte merchandise. When you click on the Crypto Bantam link a DGBAT image appears.  Recommend removing.

![Crypto Bantam](https://github.com/DigiByte-Core/DGBio/assets/136190014/c6fa4cdc-0b41-4875-addc-670b1609add0)
![Crypto Bantam 2](https://github.com/DigiByte-Core/DGBio/assets/136190014/f8529e1e-eca7-4fbc-a416-64a634af9143)

**Comment by ycagel** [comment]
This has been resolved through PR https://github.com/DigiByte-Core/DGBio/pull/89.
