### ISSUE TITLE
Outdated Site © Copyright

### ISSUE THREAD

**Issue by DennisPitallano** [DigiByte-Core/DGBio#88]
Copyright info. should be updated.
![image](https://github.com/DigiByte-Core/DGBio/assets/3394208/f5f03588-f396-4d2d-b139-f82ead0247c8)

To:
© Copyright DigiByte 2013 - 2024

**Comment by ycagel** [comment]
@DennisPitallano, are you able to submit a PR to fix this? Thank you.

**Comment by DennisPitallano** [comment]
Yep, I'll include it to my PR today

**Comment by ycagel** [comment]
This has been resolved through PR https://github.com/DigiByte-Core/DGBio/pull/89.
