### ISSUE TITLE
Store / Trade. 

### ISSUE THREAD

**Issue by DGBNOOB** [DigiByte-Core/DGBio#92]
This issue is being opened to address issue #65 which was closed. This issue offers an alternative recommendations, since there have been changes in circumstances such as DigiAssetX inc going out of business, however, there are plans being discussed for a new exchange by community members. Leave DigiAssetX in place until the website is no longer in service.  

Recommendations: 
1. Remove "Use the DigiByte Mobile application to send, accept and store your assets or explore the" and Modifying the sentence to read "Visit DigiAssets supported services to buy, sell and swap DigiAssets". 
2. Remove the link from DigiAsset supported services since it only moves to the next section.

By making this modification users are directed to DigiAsset supported services on this website instead of directing them to a wallet which doesn't support v3 digiassets, no longer available or websites that may potentially be taken offline due to going out of business. DigiAsset supported services section can be updated as service add DigiAsset Core, latest version of DigiAssets or removed if they are no longer in service.  

![store trade](https://github.com/DigiByte-Core/DGBio/assets/136190014/0a439b7e-b5de-475d-ba9b-3d6a07cdeba5)

**Comment by ycagel** [comment]
What do you think @Sbosvk?

**Comment by DennisPitallano** [comment]
Should we go ahead with the requested change?
Are we moving forward with the requested change? This affects other languages too, so I've generated translations using AI below.

translation of "Visit DigiAssets supported services to buy, sell, and swap DigiAssets."

1. Afrikaans: Besoek DigiAssets-ondersteunde dienste om DigiAssets te koop, verkoop, en ruil.
2. Albanian: Vizitoni shërbimet e mbështetura nga DigiAssets për të blerë, shitur dhe shkëmbyer DigiAssets.
3. Armenian: Այցելեք DigiAssets-ի աջակցված ծառայություններին, որպեսզի գնել, վաճառել և փոխանակել DigiAssets-ները։
4. Azerbaijani: DigiAssets-in dəstəklədiyi xidmətlərə baş çəkin, DigiAssets-i almaq, satmaq və mübadilə etmək üçün.
5. Bengali: ডিজিএসেট সমর্থিত সেবা পেতে ডিজিএসেট কেনা, বিক্রি এবং পরিবর্তন করুন।
6. Belarusian: Наведайцеся ў падтрымліваемыя паслугі DigiAssets, каб купляць, прадаваць і абмяняць DigiAssets.
7. Bosnian: Posjetite DigiAssets podržane usluge da kupujete, prodajete i mijenjate DigiAssets.
8. Bulgarian: Посетете поддържаните от DigiAssets услуги, за да купите, продадете и замените DigiAssets.
9. Burmese: DigiAssets ကို ဝယ်၍၊ ရောင်း၍နှင့် DigiAssets ကိုဖြန့်ပေးရန် DigiAssets ထောက်ခံရန် DigiAssets အင်္ဂလိပ်ကို သွားပါ။
10. Catalan: Visiteu els serveis compatibles amb DigiAssets per comprar, vendre i intercanviar DigiAssets.
11. Croatian: Posjetite DigiAssets podržane usluge kako biste kupili, prodali i zamijenili DigiAssets.
12. Czech: Navštivte služby podporované DigiAssets pro nákup, prodej a výměnu DigiAssets.
13. Danish: Besøg DigiAssets-understøttede tjenester for at købe, sælge og bytte DigiAssets.
14. Dutch: Bezoek de door DigiAssets ondersteunde services om DigiAssets te kopen, verkopen en ruilen.
15. Estonian: Külastage DigiAssetsi toetatud teenuseid DigiAssetsi ostmiseks, müümiseks ja vahetamiseks.
16. Filipino: Bisitahin ang mga suportadong serbisyo ng DigiAssets upang bumili, magbenta, at makipagpalitan ng DigiAssets.
17. Finnish: Vieraile DigiAssets-tuetuissa palveluissa ostamaan, myymään ja vaihtamaan DigiAssets.
18. Georgian: ესენით DigiAssets-ის მხარდაჭერით მხარეებს, რომ ყიდვა, გაყიდვა და შეცვლა DigiAssets.
19. Greek: Επισκεφθείτε τις υποστηριζόμενες υπηρεσίες του DigiAssets για να αγοράσετε, να πουλήσετε και να ανταλλάξετε DigiAssets.
20. Gujarati: DigiAssets સમર્થિત સેવાઓ પર યાત્રા કરો DigiAssets ખરીદવા, વેચવા અને બદલવા માટે.
21. Haitian Creole: Vizite sèvis ki sipòte pa DigiAssets yo pou achte, vann, ak chanje DigiAssets yo.
22. Hungarian: Látogasson el a DigiAssets által támogatott szolgáltatásokhoz DigiAssets vásárlásához, eladásához és cseréjéhez.
23. Icelandic: Heimsækjið DigiAssets-studdu þjónustu til að kaupa, selja og skipta um DigiAssets.
24. Indonesian: Kunjungi layanan yang didukung DigiAssets untuk membeli, menjual, dan menukar DigiAssets.
25. Irish: Tabhair cuairt ar sheirbhísí atá tacaíochta ag DigiAssets chun DigiAssets a cheannach, a dhíol, agus a athrú.
26. Italian: Visita i servizi supportati da DigiAssets per acquistare, vendere e scambiare DigiAssets.
27. Javanese: Lakuake layanan sing digolongake déning DigiAssets kanggo tuku, ngadegak, lan ndadèkake DigiAssets.
28. Kannada: DigiAssets ಬೆಂಬಲಿತ ಸೇವೆಗಳಿಗೆ ಭೇಟಿಯಿಡಿ DigiAssets ಖರೀದಿಸಲು, ಮಾರಾಟ ಮಾಡಲು ಮತ್ತು ಬದಲಾಯಿಸಲು.
29. Kazakh: DigiAssets-тің қолдау көрсететін қызметтерін қолданып, DigiAssets-ті сатып алу, сату және ауыстыруға бару үшін келіңіз.
30. Khmer: ទស្សនារាជសស្តិ៍តាមរយៈសេវាកម្មដោយ DigiAssets ដើម្បីទិញ, លក់ និង ជំនួសការផ្លាស់ប្តូរ DigiAssets។
31. Kyrgyz: DigiAssets-ти үчүн үнөмдөгүлүк көрсөтүүлөрдү караңыз, DigiAssets сатып алуу, сатуу жана алмастыруу үчүн.
32. Lao: ຈໍານວນຟອມທີ່ມີການບໍລິການຂອງ DigiAssets ສຳ ລັບການຊື້, ຂາຍ ແລະ ປ່ຽນກັນ DigiAssets ອ່ານເດີ.
33. Latin: Visitare DigiAssets servitia ut emere, vendere et commutare DigiAssets.
34. Latvian: Apmeklējiet DigiAssets atbalstītās pakalpojumus, lai iegādātos, pārdotu un mainītu DigiAssets.
35. Lithuanian: Apsilankykite DigiAssets palaikomose paslaugose, kad galėtumėte pirkti, parduoti ir keisti DigiAssets.
36. Luxembourgish: Besicht déi vun DigiAssets ënnerstetzte Servicer fir DigiAssets ze kafen, verkafen a schécken.
37. Macedonian: Посетете ги услугите кои ги поддржува DigiAssets за да купите, продадете и замените DigiAssets.
38. Malagasy: Miantso ny fampahalalana mitondra ny DigiAssets mba hanaovana fitsipika, fiaraha-miasa sy mandray anjara amin'ny DigiAssets.
39. Malay: Lawati perkhidmatan yang disokong oleh DigiAssets untuk membeli, menjual, dan menukar DigiAssets.
40. Malayalam: DigiAssets വാങ്ങാനും, വിറ്റുകയും, മാറ്റാനും താങ്കൾക്ക് സഹായിക്കുന്ന സേവനങ്ങളിൽ സന്ദർശിക്കുക.
41. Maltese: Żur is-servizzi sostnuti minn DigiAssets biex tixtri, tbiegħ u tibdel DigiAssets.
42. Marathi: खरेदी, विक्री आणि सुट्ट्या करण्यासाठी DigiAssets समर्थित सेवांवर भेट द्या.
43. Mongolian: DigiAssets -г сунгах, зарлах, DigiAssets -ийг солих зорилгоор DigiAssets -г дэмждэг үйлчилгээр дамжуулна уу.
44. Nepali: खरीद, बेच र स्वप गर्नका लागि DigiAssets समर्थित सेवा भ्रमण गर्नुहोस्।
45. Norwegian: Besøk DigiAssets-støttede tjenester for å kjøpe, selge og bytte DigiAssets.
46. Pashto: د خریداری، پلور او DigiAssets راوړلو لپاره DigiAssets سمبال شوی خدماتو ته ورځ دې.
47. Persian: از خدمات پشتیبانی شده توسط DigiAssets برای خرید، فروش و معامله DigiAssets بازدید کنید.
48. Punjabi: DigiAssets ਖਰੀਦਣ ਲਈ, ਵੇਚਣ ਲਈ ਅਤੇ ਬਦਲਣ ਲਈ DigiAssets ਦੀ ਸਹਾਇਕ ਸੇਵ

**Comment by DGBNOOB** [comment]
I recommend we move forward with the change. That was great initiative of translating the changes, as far as I know I think there are only 36 language versions on the website. There has been discussions about translations and that will require native language speakers to proofread. I see what you’re saying though, this change should be made in all the languages. I say make the changes and then when we’re done with all the changes we can start asking for proofreading. @Sbosvk what do you think?

**Comment by DennisPitallano** [comment]
> I recommend we move forward with the change. That was great initiative of translating the changes, as far as I know I think there are only 36 language versions on the website. There has been discussions about translations and that will require native language speakers to proofread. I see what you’re saying though, this change should be made in all the languages. I say make the changes and then when we’re done with all the changes we can start asking for proofreading. @Sbosvk what do you think?

I'll remove any translations that don't belong and add any missing ones. I simply copied the list from the AI's response. 😊

**Comment by DennisPitallano** [comment]
I've gone ahead and made the changes, including translations for other languages. Now we just need to give these translations a good proofread. 📑🧑‍💻😊

1. **Afrikaans**: Besoek DigiAssets-ondersteunde dienste om DigiAssets te koop, verkoop, en ruil.
2. **zech**: Navštivte služby podporované DigiAssets pro nákup, prodej a výměnu DigiAssets.
3. **Danish**: Besøg DigiAssets-understøttede tjenester for at købe, sælge og bytte DigiAssets.
4. **German**: Besuchen Sie die von DigiAssets unterstützten Dienste, um DigiAssets zu kaufen, zu verkaufen und zu tauschen.
5. **Spanish**: Visita los servicios compatibles con DigiAssets para comprar, vender e intercambiar DigiAssets.
6. **French**: Visitez les services pris en charge par DigiAssets pour acheter, vendre et échanger des DigiAssets.
7. **Croatian**: Posjetite DigiAssets podržane usluge kako biste kupili, prodali i zamijenili DigiAssets.
8. **Indonesian**: Kunjungi layanan yang didukung DigiAssets untuk membeli, menjual, dan menukar DigiAssets.
9. **Italian**: Visita i servizi supportati da DigiAssets per acquistare, vendere e scambiare DigiAssets.
10. **Swahili**: Tembelea huduma zinazoungwa mkono na DigiAssets kununua, kuuza na kubadilisha DigiAssets.
11. **Hungarian**: Látogasson el a DigiAssets által támogatott szolgáltatásokhoz DigiAssets vásárlásához, eladásához és cseréjéhez.
12. **Malay**: Lawati perkhidmatan yang disokong oleh DigiAssets untuk membeli, menjual, dan menukar DigiAssets.
13. **Dutch**: Bezoek de door DigiAssets ondersteunde services om DigiAssets te kopen, verkopen en ruilen.
14. **Norwegian**: Besøk DigiAssets-støttede tjenester for å kjøpe, selge og bytte DigiAssets.
15. **Filipino**: Bisitahin ang mga suportadong serbisyo ng DigiAssets upang bumili, magbenta, at makipagpalitan ng DigiAssets.
16. **Polish**: Odwiedź usługi obsługiwane przez DigiAssets, aby kupować, sprzedawać i wymieniać DigiAssets.
17. **Portuguese**: Visite os serviços suportados pela DigiAssets para comprar, vender e trocar DigiAssets.
18. **Romanian**: Vizitați serviciile suportate de DigiAssets pentru a cumpăra, vinde și schimba DigiAssets.
19. **Albanian**: Vizitoni shërbimet e mbështetura nga DigiAssets për të blerë, shitur dhe shkëmbyer DigiAssets.
20. **Slovenian**: Obiščite storitve, ki jih podpira DigiAssets, za nakup, prodajo in zamenjavo DigiAssets.
21. **Finnish**: Vieraile DigiAssets-tuetuissa palveluissa ostamaan, myymään ja vaihtamaan DigiAssets.
22. **Swedish**: Besök DigiAssets-stödda tjänster för att köpa, sälja och byta DigiAssets.
23. **Vietnamese**: Truy cập các dịch vụ được hỗ trợ bởi DigiAssets để mua, bán và trao đổi DigiAssets.
24. **Turkish**: DigiAssets destekli hizmetleri ziyaret ederek DigiAssets satın alabilir, satabilir ve takas edebilirsiniz.
25. **Russian**: Посетите сервисы, поддерживаемые DigiAssets, чтобы покупать, продавать и обменивать DigiAssets.
26. **Bulgarian**: Посетете поддържаните от DigiAssets услуги, за да купите, продадете и замените DigiAssets.
27. **Greek**: Επισκεφθείτε τις υποστηριζόμενες υπηρεσίες του DigiAssets για να αγοράσετε, να πουλήσετε και να ανταλλάξετε DigiAssets.
28. **Hindi**: DigiAssets समर्थित सेवाओं का दौरा करें ताकि DigiAssets खरीदें, बेचें और बदलें।
29. **Thai**: เข้าชมบริการที่รองรับโดย DigiAssets เพื่อซื้อ, ขาย และแลกเปลี่ยน DigiAssets
30. **Japanese**: DigiAssets を購入、販売、および交換するための DigiAssets サポートサービスをご覧ください。
31. **Korean**: DigiAssets를 구매, 판매 및 교환할 수 있는 DigiAssets 지원 서비스를 방문해보세요.
32. **Chinese** (Simplified): 访问 DigiAssets 支持的服务以购买、出售和交换 DigiAssets。
33. **Arabic**: قم بزيارة الخدمات المدعومة لـ DigiAssets لشراء وبيع وتبادل DigiAssets.

**Comment by DGBNOOB** [comment]
Awesome. Just counted and it’s 35 languages on the website, let me try to identify the two remaining not on this list, however, the main thing is removing the anchor on all of the language versions and once the other 2 are identified, we can remove DigiByte mobile wallet and update translation. Proofreading will be a challenge but doable. @Sbosvk made a suggestion about narrowing down on just a few language versions, glad this wasn’t a major rewrite.

**Comment by DGBNOOB** [comment]
The two languages not on this list are Persian and English, these two make 35. So really only need Persian.

**Comment by DennisPitallano** [comment]
> The two languages not on this list are Persian and English, these two make 35. So really only need Persian.

Yes, I forgot to include Persian in the list, but the translation has been updated. I omitted English from the list since it is the default language.

**Comment by ycagel** [comment]
This has been resolved through PR https://github.com/DigiByte-Core/DGBio/pull/99.
