### ISSUE TITLE
Apps developed by a Third-Party service. Software wallets

### ISSUE THREAD

**Issue by DGBNOOB** [DigiByte-Core/DGBio#94]
Recommend removing Jaxx Liberty wallet since it was recently retired and if you click on the download link it will state wallet retired. 

![Jaxx Liberty](https://github.com/DigiByte-Core/DGBio/assets/136190014/c74a1ea4-077a-4f9e-8bd3-e812253f1ff9)
Retired
![Screenshot 2024-03-22 103209](https://github.com/DigiByte-Core/DGBio/assets/136190014/3df68047-9506-4df4-b6eb-d88ce93b7cda)

**Comment by ycagel** [comment]
This has been resolved through PR https://github.com/DigiByte-Core/DGBio/pull/97.
