### ISSUE TITLE
Discover Digi-ID supported services

### ISSUE THREAD

**Issue by DGBNOOB** [DigiByte-Core/DGBio#95]
Recommend removing absolute jobs from see Digi-ID in action section. It was brought up in a discussion that absolute jobs doesn't use Digi-ID in their service and it was verified by three different people.

![Screenshot 2024-03-22 091650](https://github.com/DigiByte-Core/DGBio/assets/136190014/4c3650b1-8989-4bab-ae0b-7151d5e76c34)

**Comment by ycagel** [comment]
This has been resolved through PR https://github.com/DigiByte-Core/DGBio/pull/97.
