### ISSUE TITLE
Digi-ID supported services AntumID

### ISSUE THREAD

**Issue by DGBNOOB** [DigiByte-Core/DGBio#96]
When you click on the link message appears stating website not secure and could lead to attackers trying to lead to stealing information. 

Recommendations:

Reach out to AntumID to see if they plan on updating security certificates and if they don't plan on it recommend removing it from this website.
![antumid io](https://github.com/DigiByte-Core/DGBio/assets/136190014/23f34ce3-007d-4233-9725-4449887cbf86)

**Comment by ycagel** [comment]
My personal opinion is to not include any commercial products like AntumID to our website.

**Comment by DGBNOOB** [comment]
The way look at it is if the website allows Digi-ID logins then it adds to utility and adds to login authentication use case, however, I wouldn’t know since we’re get an error message that the site is not secure. For that I’d be more inclined to say remove it since that’s what visitors to DigiByte .org are currently seeing.

**Comment by DennisPitallano** [comment]
While visiting the unsafe website, I observed that the AntumID Platform had already been deprecated.
![screencapture-antumid-be-2024-03-25-16_50_30](https://github.com/DigiByte-Core/DGBio/assets/3394208/9568384f-4cfc-42c4-97c2-2c6b992cfd13)

**Comment by ycagel** [comment]
This has been resolved through PR https://github.com/DigiByte-Core/DGBio/pull/97.
